export const ADD_SERVICE = 'ADD_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';

export const EDIT_SERVICE = 'EDIT_SERVICE';
export const CANSEL_FIELD = 'CANSEL_FIELD';
export const CHANGE_FILTER_LIST = 'CHANGE_FILTER_LIST';

export const FETCH_SERVICES_REQUEST = 'FETCH_SERVICES_REQUEST';
export const FETCH_SERVICES_FAILURE = 'FETCH_SERVICES_FAILURE';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS'
export const FETCH_SERVICE_REMOVE = 'FETCH_SERVICE_REMOVE';